export const initialOwnerProducts = [
  {
    id: 'PROD-101',
    name: 'Country Sourdough Batard',
    category: 'Loaves & Buns',
    price: 12.0,
    availableQuantity: 15,
    activeMenu: true,
    image: 'https://lh3.googleusercontent.com/aida/AEtjO1VKpJOgOByKk7UZF-MBSFBIW3sDApKHBfHTv7vcB9x-53lK9or9JxnqPJrr0KhMfqr3A4xsXbbnbcIg3_lzkS9URQdPED23mQYotwik3rPDwkgm-wdox5y2cApCNimfW9SebXeaA7b1xlrYS0mFIkIEdhZRp8175HVbZIxS_qN5IGYHpNMIJO9tXKQw3HrwfbVcaugNEBIXGa1rcEj2MEySJHq38aBRTh5G-vm9O9R35kpMqOSpeox8k3Q',
    ingredients: 'Cairnspring Yecora Rojo Flour, Sourdough Culture, Sea Salt',
    description: 'Blistered dark crust with open custard crumb fermentation.',
  },
  {
    id: 'PROD-102',
    name: 'Cardamom Morning Buns',
    category: 'Loaves & Buns',
    price: 6.5,
    availableQuantity: 28,
    activeMenu: true,
    image: 'https://lh3.googleusercontent.com/aida/AEtjO1UhIxCBIJjQvr2M3VZAPcw6MPiZ5a-smNCBqCn1Y2IFfGgjRvQMQt2M-Fn-7bZFTK6ZlAhq_ayXF1vg9_EKIKgh_78-U2C9IRJfNjZQpNGjvBKFghGoYaNZzMAYtYGtJAHKPD1bJiSg9WFiwnO3jKkzrk2cRkGac0UE8lSPiA3qyOL_uTTcuk4A5Swg__Y7LVvPjrn9kdBsig3L8Cn2aARskohFm7q0_E1B5O2LsTxbkv6qe_-ofZSUdaM',
    ingredients: 'Hard Wheat Flour, Normandy Cultured Butter, Green Cardamom Pods, Wildflower Honey',
    description: 'Freshly ground cardamom pods with Swedish pearl sugar.',
  },
  {
    id: 'PROD-103',
    name: 'Dark Chocolate Fudge Cake',
    category: 'Cakes',
    price: 34.0,
    availableQuantity: 5,
    activeMenu: true,
    image: 'https://lh3.googleusercontent.com/aida/AEtjO1U6wA_Ns6O1LwDryFuDDHDdIIu1ctaoYkJhbFO408nCvU26ILS1uTRimR7bKsknZ55DoO-RzHKg9nv424IzNwsi58sUu0oylY6oE3JgemWRksi93Q52GQfufAl0Cm22O7U-6-EvrVJyg0rNOCLa0aJxoRkH3Wa3QrroEwcuZjywHfTEVtwyswHt_4HzPpNJ4nfs_lun5KRwAppgc0ZfTJuAlOdnF7asU-jnogioyiITpFQcBlmN9A-J77Y',
    ingredients: 'Valrhona Dark Cocoa, Cultured Butter, Wildflower Honey, Stone Ground Rye',
    description: 'Rich dark chocolate layers with glossy cocoa ganache.',
  },
  {
    id: 'PROD-104',
    name: 'Classic Vanilla Bean Cake',
    category: 'Cakes',
    price: 32.0,
    availableQuantity: 0,
    activeMenu: false,
    image: 'https://lh3.googleusercontent.com/aida/AEtjO1V5kRAUyRtMEPazJhImo5jwxZfapQ1V8W-2vMcGpK8_SVVUoCGlO6U8P4NXX3MgRLo65DTAP4hbS85igraIlummQq_5i8GuOf26mBAJxKfiMSCFMVqmac2ZXTlmf7T0TFCC1jkOo7sapNuXsC7MueVxknJp7nBQi5gz_SPENWknu91MegPyhTKBra9BA-loBNUcewWPEbAQ2dz1C4Xlw3yVD3D_KIZkdvL_adaowT9j5Q5su3GmTNYm_jM',
    ingredients: 'Madagascar Vanilla Beans, Cultured Butter, Pastry Flour, Chamomile Blossoms',
    description: 'Whipped buttercream frosting with organic chamomile blossoms.',
  },
  {
    id: 'PROD-105',
    name: 'Artisan Red Velvet Cupcakes',
    category: 'Cupcakes',
    price: 4.5,
    availableQuantity: 40,
    activeMenu: true,
    image: 'https://lh3.googleusercontent.com/aida/AEtjO1XkzdURPwREMdKa83zbeVsM0opPZxL0aYpdtBYcb37XxH5qao_t9WTnsWPsg1uLpAPDFh6ReSFIpuVgXH6OCt0b6mtm82CWwqzS1a_HPQr21dBA_xoAVkzOcUmhbNbseLCb4WIwCW5IGhvpr2MU8-ZFbal6iDSm2O-pPfLq3QUlGPfGneMHjVBGXryF5Nt4Hfs2TDAYmag_0XyTLDNEsUfVyqC_r-7Nyxb0dcrUAchtprYncarOj7eQig',
    ingredients: 'Unbleached Wheat Flour, Cocoa, Cream Cheese Frosting',
    description: 'Piped swirls of cream cheese frosting on wooden parchment cups.',
  },
  {
    id: 'PROD-106',
    name: 'Fudgy Sea Salt Brownies',
    category: 'Brownies',
    price: 5.5,
    availableQuantity: 22,
    activeMenu: true,
    image: 'https://lh3.googleusercontent.com/aida/AEtjO1Vubnww0tDF7Wkg8CkXCGK-dfdX3D1xrKHId5pam3hSIr4gDT5EL6FqEL2JD6AeVA8DRTuEdfx-fKI9HZgFBDgoQxOdvmcNPqDtfVphYTShtOby5xD_jPi94BB9D6Sjtn8bfI5EpPg4N0b8IYqZIK2SVgkhZNH7BFYseo-m430_cgL1jw9d_HKafQtiLD3zx_TzoTc6sGS4hfKWher_jbOoxzqRM1aQyJnv4GIPAeRWdSngSad8XIQ3I_U',
    ingredients: 'Valrhona Cocoa Nibs, Cultured Butter, Maldon Sea Salt',
    description: 'Flaky crinkly top squares dusted with Maldon sea salt.',
  },
];
