/**
 * Crumb & Bloom Artisan Bakery — Product Mock Data
 * Aligned with client/DESIGN.md & client/FRONTEND_RULES.md
 *
 * Categories: Cakes, Cupcakes, Brownies, Loaves & Buns
 * Monospaced numerical values: prices, hydration %, weights
 */

export const PRODUCT_CATEGORIES = [
  { id: 'all', label: 'All Offerings' },
  { id: 'loaves-buns', label: 'Loaves & Buns' },
  { id: 'cakes', label: 'Cakes' },
  { id: 'cupcakes', label: 'Cupcakes' },
  { id: 'brownies', label: 'Brownies' },
];

export const MOCK_PRODUCTS = [
  {
    id: 'prod-country-sourdough',
    name: 'Country Sourdough Boule',
    category: 'loaves-buns',
    categoryLabel: 'Loaves & Buns',
    tagline: 'Naturally leavened with wild orchard yeast and stone-milled heritage grain',
    description:
      'Our signature hearth loaf. Crafted from Cairnspring Mills organic Yecora Rojo wheat and stone-ground Edison hard white flour. Features an open, custardy crumb, blistered mahogany crust, and balanced lactic tang.',
    price: 14.0,
    weight: '850g',
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=1000&q=80',
    available: true,
    remainingAllotment: 6,
    totalBatchCap: 28,
    hydration: '82%',
    fermentation: '36-Hour Cold Levain Fermentation',
    flourProvenance: 'Cairnspring Mills (Skagit Valley, WA) — Organic Yecora Rojo & Edison Hard White',
    allergens: ['Wheat / Gluten'],
    featured: true,
    bakerNotes: 'Best sliced with a serrated knife 4 hours after cooling. Keeps fresh on the counter for 5 days in linen.',
  },
  {
    id: 'prod-seeded-heritage-rye',
    name: 'Seeded Heritage Rye Batard',
    category: 'loaves-buns',
    categoryLabel: 'Loaves & Buns',
    tagline: 'Whole-grain dark rye crusted in toasted pumpkin, sunflower, and golden flax',
    description:
      'Dense, aromatic, and deeply nourishing. Naturally soured for 48 hours using our 100-year Rye mother culture. Rolled generously in toasted organic seeds with a hint of roasted caraway.',
    price: 16.0,
    weight: '900g',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1000&q=80',
    available: true,
    remainingAllotment: 3,
    totalBatchCap: 16,
    hydration: '85%',
    fermentation: '48-Hour Heritage Sourdough Proof',
    flourProvenance: 'Cairnspring Mills Organic Whole Rye & Trailblazer Bread Flour',
    allergens: ['Wheat / Gluten', 'Rye', 'Sesame / Seeds'],
    featured: true,
    bakerNotes: 'Flavor matures over 48 hours. Phenomenal paired with cultured butter, smoked sea salt, and aged cheddar.',
  },
  {
    id: 'prod-rosemary-garlic-focaccia',
    name: 'Rosemary & Confit Garlic Focaccia',
    category: 'loaves-buns',
    categoryLabel: 'Loaves & Buns',
    tagline: 'High-hydration pan bread with slow-roasted garlic and orchard rosemary',
    description:
      'Dimpled by hand and steeped in California extra virgin olive oil. Topped with fragrant fresh-picked garden rosemary, whole caramelized confit garlic cloves, and flaky Maldon sea salt crystals.',
    price: 12.0,
    weight: '650g',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1000&q=80',
    available: true,
    remainingAllotment: 8,
    totalBatchCap: 20,
    hydration: '88%',
    fermentation: '24-Hour Cold Pan Retardation',
    flourProvenance: 'Shepherd’s Grain High Protein Unbleached Flour',
    allergens: ['Wheat / Gluten'],
    featured: false,
    bakerNotes: 'Reheat in a 400°F oven for 6 minutes to restore the crispy, olive-oil fried bottom crust.',
  },
  {
    id: 'prod-cardamom-morning-bun',
    name: 'Cardamom Sourdough Morning Bun',
    category: 'loaves-buns',
    categoryLabel: 'Loaves & Buns',
    tagline: 'Laminated slow-ferment brioche rolled in green cardamom sugar',
    description:
      'Laminated with European high-fat cultured butter and folded with crushed Malabar green cardamom pods. Rolled into spirals, baked until deeply caramelized, and tossed in vanilla bean sugar.',
    price: 6.5,
    weight: '160g',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=1000&q=80',
    available: true,
    remainingAllotment: 4,
    totalBatchCap: 32,
    hydration: '68%',
    fermentation: '20-Hour Laminated Brioche Proof',
    flourProvenance: 'Organic Artisan Baker’s Craft & Grass-Fed Dairy',
    allergens: ['Wheat / Gluten', 'Dairy', 'Egg'],
    featured: true,
    bakerNotes: 'Flaky layers with a soft, cardamom-perfumed interior. Best enjoyed the morning of pickup.',
  },
  {
    id: 'prod-brown-butter-olive-oil-cake',
    name: 'Brown Butter & Blood Orange Olive Oil Cake',
    category: 'cakes',
    categoryLabel: 'Cakes',
    tagline: 'Single-origin olive oil crumb scented with nutty browned butter and citrus',
    description:
      'Moist, tender single-layer hearth cake made with stone-ground Einkorn flour, nutty browned European butter, and cold-pressed Sevillano olive oil. Finished with a crystalline blood orange glaze.',
    price: 38.0,
    weight: '1100g (8-inch round)',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=80',
    available: true,
    remainingAllotment: 2,
    totalBatchCap: 10,
    hydration: 'N/A (Cake Emulsion)',
    fermentation: 'Cultured Buttermilk Resting',
    flourProvenance: 'Bluebird Grain Farms Organic Whole Einkorn & Unbleached Pastry Flour',
    allergens: ['Wheat / Gluten', 'Dairy', 'Egg'],
    featured: true,
    bakerNotes: 'Serves 8-10. Holds exceptionally well at room temperature for up to 4 days as flavors meld.',
  },
  {
    id: 'prod-valrhona-sourdough-brownies',
    name: 'Valrhona 70% Dark Sourdough Brownies',
    category: 'brownies',
    categoryLabel: 'Brownies',
    tagline: 'Fudgy, dense squares infused with ripe sourdough starter and sea salt',
    description:
      'Rich, glossy, crackly-topped brownies baked with melted Valrhona Guanaja 70% dark chocolate and aged sourdough discard. The natural fermentation balances the intense chocolate richness.',
    price: 5.5,
    weight: '140g each',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1000&q=80',
    available: true,
    remainingAllotment: 12,
    totalBatchCap: 30,
    hydration: 'N/A',
    fermentation: '12-Hour Starter Discard Maceration',
    flourProvenance: 'Cairnspring Mills Edison Wheat & Valrhona Cocoa',
    allergens: ['Wheat / Gluten', 'Dairy', 'Egg'],
    featured: false,
    bakerNotes: 'Ultra-fudgy center with a papery crust. Pair with espresso or cold whole milk.',
  },
  {
    id: 'prod-spiced-carrot-cupcakes',
    name: 'Heritage Spiced Carrot Cupcakes (Box of 4)',
    category: 'cupcakes',
    categoryLabel: 'Cupcakes',
    tagline: 'Heirloom carrots, toasted Oregon walnuts, and whipped cultured cream cheese',
    description:
      'Tender spiced crumb loaded with freshly grated heirloom carrots, cinnamon, nutmeg, and toasted Oregon walnuts. Swirled with tangy, house-cultured cream cheese frosting and bee pollen dust.',
    price: 18.0,
    weight: '4 x 110g',
    imageUrl: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=1000&q=80',
    available: true,
    remainingAllotment: 5,
    totalBatchCap: 15,
    hydration: 'N/A',
    fermentation: 'Cultured Cream Cheese Cultivation',
    flourProvenance: 'Organic Sprouted Spelt & Pastry Flour',
    allergens: ['Wheat / Gluten', 'Dairy', 'Egg', 'Tree Nuts (Walnuts)'],
    featured: false,
    bakerNotes: 'Packaged in breathable kraft bakery boxes with twine. Keep chilled until 30 minutes before serving.',
  },
  {
    id: 'prod-toasted-sesame-brioche-buns',
    name: 'Toasted Sesame Brioche Buns (Pack of 4)',
    category: 'loaves-buns',
    categoryLabel: 'Loaves & Buns',
    tagline: 'Feather-light golden brioche crowned with toasted black and white sesame',
    description:
      'Enriched with egg yolks and sweet cultured cream butter. Slow-proofed for pillowy texture and delicate shred. Perfect for artisan smash burgers or morning egg sandwiches.',
    price: 10.0,
    weight: '4 x 100g',
    imageUrl: 'https://images.unsplash.com/photo-1597079910443-60c43fc4f729?auto=format&fit=crop&w=1000&q=80',
    available: false,
    remainingAllotment: 0,
    totalBatchCap: 24,
    hydration: '72%',
    fermentation: '18-Hour Retarded Brioche Dough',
    flourProvenance: 'Shepherd’s Grain Patent Flour & Organic Butter',
    allergens: ['Wheat / Gluten', 'Dairy', 'Egg', 'Sesame'],
    featured: false,
    bakerNotes: 'Batch filled for Friday drop. Next batch opens for Tuesday reserve.',
  },
];
